### PR TITLE
Fixed incorrect function names in js-components

### LINKED ISSUE #10: Incorrect function names in js-components
Applies to collapse/dropdown/modal-dialog

### PR DESCRIPTION
**Pull request by robinlagren**
Fix #10

### CODE REVIEW

File: src/js/collapse.js [hunk 1]
```diff
@@ -103,7 +103,7 @@ const Collapse = (($) => {
          return;
       }
 
-      $target.collapse();
+      $target.envCollapse();
```
Comment (albinohrn) [inline src/js/collapse.js]: Change to `$target[NAME]` makes the connection more obvious

File: src/js/dropdown.js [hunk 2]
```diff
@@ -110,7 +110,7 @@ const Dropdown = (($) => {
       const $this = $(this);
       const $target = $($this.data('target'));
 
-      $target.dropdown();
+      $target.envDropdown();
```
Comment (albinohrn) [inline src/js/dropdown.js]: Same here `$target[NAME]`

File: src/js/modal-dialog.js [hunk 3]
```diff
@@ -214,7 +214,7 @@ const ModalDialog = (($) => {
 
       const $target = $($(this).data('target'));
 
-      $target.modalDialog();
+      $target.envDialog();
```
Comment (albinohrn) [inline src/js/modal-dialog.js]: And here `$target[NAME]`
